# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  tag: '$(Build.BuildId)'

steps:
- script: |
    docker build -f $(Build.SourcesDirectory)/Dockerfile -t $(dockerId)/karakapli-storefront:$(tag) .
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/karakapli-storefront:$(tag)
  env:
    pswd: $(dockerHubPwd)
